rvm:
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"

script:
  - bundle exec rspec ./spec
  - BUNDLE_GEMFILE=gemfiles/activesupport3.gemfile bundle install
  - BUNDLE_GEMFILE=gemfiles/activesupport3.gemfile bundle exec rspec ./spec
